package com.jwcrain.sandcastle;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.jwcrain.sandcastle.App;
import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasQuicksort() {
        App classUnderTest = new App();
    }
}
